version: "3.3"
networks:
  backend:
    driver: bridge
services:
  app:
    container_name: backend
    build:
      context: .
      dockerfile: Slicecake-backend/Dockerfile
    ports:
      - 8080:80
    networks:
      - backend
    depends_on:
      - postgress
  postgress:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "terrarik22"
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: umbrellamixmail@gmail.com
      PGADMIN_DEFAULT_PASSWORD: terrarik22
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5433:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgress
volumes:
  postgres-data:
  pgadmin:


